LIB_CPPFLAGS = @LIB_CPPFLAGS@
SETEGID = 
LIBDIR = ${libdir}
libdatadir = /home/chris/Src/poschengband/lib/
vardatadir = /home/chris/Src/poschengband/lib/
docdatadir = /home/chris/Src/poschengband/doc/
configdir = /home/chris/Src/poschengband/lib/
pdfdir ?= ${docdir}
ECHO_N ?= -n
bindir ?= ..
dvidir ?= ${docdir}
datadir ?= ${datarootdir}
CPPFLAGS ?=  -I.
SHELL ?= /bin/bash
program_transform_name ?= s,x,x,
DEFS ?= -DHAVE_CONFIG_H
infodir ?= ${datarootdir}/info
libexecdir ?= ${exec_prefix}/libexec
localedir ?= ${datarootdir}/locale
LTLIBOBJS ?= 
LDFLAGS ?=  -lncurses
includedir ?= ${prefix}/include
libdir ?= ${exec_prefix}/lib
localstatedir ?= ${prefix}/var
docdir ?= /home/chris/Src/poschengband/doc/
INSTALL_SCRIPT ?= ${INSTALL}
MV ?= /bin/mv
GLIB_LIBS ?= @GLIB_LIBS@
sharedstatedir ?= ${prefix}/com
GTK_CFLAGS ?= @GTK_CFLAGS@
OBJEXT ?= o
PKG_CONFIG ?= @PKG_CONFIG@
sysconfdir ?= ${prefix}/etc
htmldir ?= ${docdir}
PACKAGE_STRING ?= PosChengband 2.0.1
sbindir ?= ${exec_prefix}/sbin
CP ?= /bin/cp
SET_MAKE ?= 
ECHO_C ?= 
psdir ?= ${docdir}
oldincludedir ?= /usr/include
GTK_LIBS ?= @GTK_LIBS@
mandir ?= ${datarootdir}/man
PACKAGE_NAME ?= PosChengband
ECHO_T ?= 
LIBOBJS ?= 
ac_ct_CC ?= gcc
PACKAGE_VERSION ?= 2.0.1
LN_S ?= ln -s
GREP ?= /bin/grep
INSTALL_DATA ?= ${INSTALL} -m 644
datarootdir ?= ${prefix}/share
RM ?= /bin/rm
INSTALL_PROGRAM ?= ${INSTALL}
exec_prefix ?= /usr/local
EGREP ?= /bin/grep -E
prefix ?= /usr/local
RC ?= no
VERSION ?= @VERSION@
MAINFILES = $(BASEMAINFILES) $(X11MAINFILES)
USE_STATS = 
DISTCLEAN = doc/manual/manual.pdf
